//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Urun_Takip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_MUSTERI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MUSTERI()
        {
            this.TBL_SATIS = new HashSet<TBL_SATIS>();
        }
    
        public int musteriid { get; set; }
        [Required(ErrorMessage ="Bu Alaný Boþ Býrakamazsýnýz!")]
        [StringLength(50,ErrorMessage ="En Fazla 50 Karakter Girebilirsiniz!")]
        public string musteriad { get; set; }

        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz!")]
        [StringLength(50, ErrorMessage = "En Fazla 50 Karakter Girebilirsiniz!")]
        public string musterisoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SATIS> TBL_SATIS { get; set; }
    }
}
