//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Urun_Takip.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_URUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_URUN()
        {
            this.TBL_SATIS = new HashSet<TBL_SATIS>();
        }
    
        public int urunid { get; set; }
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz!")]
        public string urunad { get; set; }
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz!")]
        public string marka { get; set; }
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz!")]
        public Nullable<int> urunkategori { get; set; }
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz!")]
        public Nullable<decimal> fiyat { get; set; }
        [Required(ErrorMessage = "Bu Alaný Boþ Býrakamazsýnýz!")]
        public Nullable<byte> stok { get; set; }
    
        public virtual TBL_KATEGORI TBL_KATEGORI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_SATIS> TBL_SATIS { get; set; }
    }
}
